### ISSUE TITLE
No Exe File, Building from Source Also Gives Error

### ISSUE THREAD

**Issue by fahdmirza** [TLAMHutto/ollamaChat#1]
Hi,  
  I dont see any exe file here plus when try to install it with pipx , it also gives error :

PIP STDOUT
----------
Collecting pychat
Downloading PyChat-1.5.0.tar.gz (22 kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'

PIP STDERR
----------
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [19 lines of output]
Traceback (most recent call last):
File "C:\Users\Administrator\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
main()
File "C:\Users\Administrator\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "C:\Users\Administrator\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
return hook(config_settings)
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-r5bvjlp1\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=[])
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-r5bvjlp1\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
self.run_setup()
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-r5bvjlp1\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
super().run_setup(setup_script=setup_script)
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-r5bvjlp1\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
exec(code, locals())
File "<string>", line 77
except Exception, e:
^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by TLAMHutto** [comment]
Hi, I added the .exe also for time being if you need to build from source just use `py main.py` in the root directory instead of pipx

**Comment by fahdmirza** [comment]
Thanks, I just reviewed it on my channel :  https://youtu.be/3rl7CySm8D8
